server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8883

logging:
  level: WARN
  loggers:
    "org.example":
      level: DEBUG
      additive: false
      appenders:
        - type: console
  appenders:
    - type: console
